# Study

The data come from the paper 
Human Activity Recognition Using Smartphones Dataset
Version 1.0
==================================================================
Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.
Smartlab - Non Linear Complex Systems Laboratory
DITEN - Universita??? degli Studi di Genova.
Via Opera Pia 11A, I-16145, Genoa, Italy.
activityrecognition@smartlab.ws
www.smartlab.ws
==================================================================

As they say, the experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist.  

Details are given in the paper.
We merged train and test set and added subject id and activity.
The original features are also reported in the data set. We took oonly the measures of meana or standard deviation. More precisely

```{r,echo=FALSE}
read.csv("variables.csv")[,2]
```
We averaged then these variables conditioned on subject and activity getting the final data.
